### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by jamestomasino** [jamestomasino/veasing#2]
These functions are predictable and pure. Tests should be added to this module.

v has simple testing built in. [documentation](https://vlang.io/docs#testing)

**Comment by ccmetz** [comment]
Hi, I could work on this issue

**Comment by jamestomasino** [comment]
@ccmetz just to let you know, I updated the code in master to use the PI & TAU constants from v's math module instead of my crappy constants. This should greatly improve precision. It will definately change results for any tests you're working on, though.

**Comment by ccmetz** [comment]
Hey wanted to give a quick update on my progress. I've added tests for the linear, quadratic, cubic, quartic, and quintic functions, but I'm seeing some weird assertion failures for 3 of them and I'm not completely sure what's causing them. I marked the failing tests with a `//FIXME` comment in case you wanted to take a look at them [here](https://github.com/ccmetz/veasing/blob/veasing-tests/veasing_test.v). I'll do some more investigating into them tomorrow.

**Comment by jamestomasino** [comment]
I'm looking through now and I see a couple things that might be an issue. First, QuarticOut(3) should be -15 as the output, not 80, according to penner's math. I'm getting -15 properly with the test, so i think that one will be correct if you change the assertion.

After that you start getting into floating point precision issues. Looking around, there's a few solutions. One Go article suggested testing for a certain tolerance:

```go
opt  := cmp.Comparer(func(x, y float64) bool {
    diff := math.Abs(x - y)
    mean := math.Abs(x + y) / 2.0
    if math.IsNaN(diff / mean) {
        return true
    }
    return (diff / mean) < tolerance
})
```

We might try adding a similar function into the tests and then using that to compare instead of strict equality.3

For instance, I get this result with the veasing module:
```
Easing.Quintic.InOut(0.6) 0.8361599999999999
```
You're trying to test it against `0.83616`. It's basically the same result, just floating point math differences.

**Comment by jamestomasino** [comment]
I quickly converted that test to v:

```v
import math

fn compare(x f64, y f64) bool {
  tolerance := 0.00001
  diff := math.abs(x - y)
  mean := math.abs(x + y) / 2.0
  if math.is_nan(diff / mean) {
      return true
  }
  return (diff / mean) < tolerance
}
```
And you can use it like: 

```v
fn test_quintic_ease_in_out_over_0_5() {
  assert compare(veasing.quintic_ease_in_out(0.6), 0.83616)
}
```

**Comment by jamestomasino** [comment]
BTW, I searched around and the following command gives much nicer verbose output on the module tests, showing the success of each test function and assertion:

`v -stats test veasing_test.v`

**Comment by jamestomasino** [comment]
After talking in discord with the maintainers, the test works best from one folder level up, outside this repo itself:

```
v -stats test veasing/
```

That will properly import the veasing module for testing and run all tests in the folder. It's a little cumbersome to leave the repo folder, but it works.

**Comment by ccmetz** [comment]
Thank you for looking into this for me! Yeah it took a bit of tinkering but I was able to come to the conclusion that running the tests from outside the repo worked best as well. That `-stats` option will come in handy! I couldn't figure out how to get more meaningful output from the tests.

**Comment by jamestomasino** [comment]
I made some readme updates and included that knowledge for posterity.

**Comment by jamestomasino** [comment]
~~whoops! and i accidentally committed your work-in-progress test file with my tweaks. Um, crap.~~

nevermind. Fixed it.

**Comment by ccmetz** [comment]
Hey I've been a bit busy with work lately but I'm getting back to working on these tests again. Hope to have a pull request in by tonight or tomorrow!
